import Navbar from "@/components/Navbar";
import "./index.css";
import { StoreProvider } from "../store/StoreProvider";
import { ToastContainer, ToastPosition } from "react-toastify";

export const metadata = {
  title: "Purchase Store",
  description: "Generated by Dhruv Hingol",
};
import NextUiProvider from "./NextUiProvider";

import "react-toastify/dist/ReactToastify.css";
import { renderIcon } from "@/components/ToastIcon";
import { Metadata } from "next";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const toastStyles = {
    background: "Green",
    borderRadius: "0.5rem",
    color: "#fff",
    fontSize: "1rem",
    padding: "0.5rem",
    fontFamily: "DM Sans",
  };

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </head>
      <body>
        <StoreProvider>
          <ToastContainer
            autoClose={2000}
            position={"top-right" as ToastPosition}
            toastClassName="bg-primary"
            closeButton={false}
            icon={renderIcon}
            toastStyle={toastStyles}
            hideProgressBar
          />
          <NextUiProvider>
            <Navbar />
            {children}
          </NextUiProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
